name: Wrapper workflow

on:
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.parse.outputs.env }}
      tag: ${{ steps.parse.outputs.tag }}
      service: ${{ steps.parse.outputs.service }}
    steps:
      - name: Simulate JSON
        run: |
          cat <<EOF > request.json
          {
            "env": "dev",
            "image_tag": "v1.2.3",
            "service": "deploy-app"
          }
          EOF

      - name: Parse JSON
        id: parse
        run: |
          echo "env=$(jq -r .env request.json)" >> $GITHUB_OUTPUT
          echo "tag=$(jq -r .image_tag request.json)" >> $GITHUB_OUTPUT
          echo "service=$(jq -r .service request.json)" >> $GITHUB_OUTPUT

  call-app:
    needs: simulate
    if: ${{ needs.simulate.outputs.service == 'deploy-app' }}
    uses: ./.github/workflows/reusable_build.yml
    with:
      environment: ${{ needs.simulate.outputs.env }}
      image_tag: ${{ needs.simulate.outputs.tag }}

 # call-db:
 #   needs: simulate
 #   if: ${{ needs.simulate.outputs.service == 'deploy-db' }}
 #   uses: ./.github/workflows/deploy-db.yml
 #   with:
 #     environment: ${{ needs.simulate.outputs.env }}
 #     image_tag: ${{ needs.simulate.outputs.tag }}
